infrawatch/sg-core

go.mod
pkg/unixserver/server.go

Just some minor ones and some (`*****`) comments about more to come. 
* FIXED - `collectd_` prefix has become `cd_`
* Trivial, just changed it back
* FIXED - New code is not propagating the collectd timestamp to the scrape endpoint
* In the old code this was optional, but I know of no good argument for
turning it off
* Added comments about internal metrics missing/misnamed

Improved compatibility w/ old SG

---

cmd/server/server.go
pkg/unixserver/server.go

* Helps if time sync is not rock-solid between the source and STF

Make timestamps optional

---

go.mod

While doing docker builds in brew we saw this error:
```
2020-11-10 18:37:56,459 - atomic_reactor.plugins.imagebuilder - INFO - Complete!
2020-11-10 18:37:56,678 - atomic_reactor.plugins.imagebuilder - INFO - --> RUN mkdir -p $GOPATH/src/github.com/infrawatch/sg-core/_build
2020-11-10 18:37:56,764 - atomic_reactor.plugins.imagebuilder - INFO - --> WORKDIR $GOPATH/src/github.com/infrawatch/sg-core
2020-11-10 18:37:56,801 - atomic_reactor.plugins.imagebuilder - INFO - --> ADD src $GOPATH/src/github.com/infrawatch/sg-core
2020-11-10 18:37:57,037 - atomic_reactor.plugins.imagebuilder - INFO - --> RUN /usr/bin/go build -mod vendor -o ./_build/server cmd/server/server.go
2020-11-10 18:37:57,204 - atomic_reactor.plugins.imagebuilder - INFO - go: inconsistent vendoring in …
```

Committing results of "go mod vendor" because it fixed my build

---

build/test-framework/run_tests.sh

Test script was running `go mod vendor` with golang 1.13 from the default Travis environment, with the source dir mounted as a volume. This removes the "explicit" tags in modules.txt [1], causing the build to fail with "	collectd.org@v0.3.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt" when it is later built for real with golang 1.14 [2]. This script should probably run tests using the same version of golang we will eventually build with.  I'm removing this line because we do the `go mod vendor` before committing now. 
[1] https://github.com/infrawatch/sg-core/blob/master/vendor/modules.txt#L2
[2] https://travis-ci.org/github/infrawatch/sg-core/builds/743489014#L1237

Matching golang version in test script

---

go.mod
plugins/application/prometheus/main.go

Prometheus collectors must be expired after all metrics have been deleted from it else Prometheus will reject new incoming metrics with the same labels

set collector expiry

---

plugins/application/elasticsearch/main.go
plugins/application/elasticsearch/pkg/lib/config.go

Fix omission of the ability to clear elastic search indices on start up if configured

Delete ES indices on startup if configured

---

plugins/handler/ceilometer-metrics/main.go
plugins/handler/ceilometer-metrics/messages/metric-tests.json

https://github.com/infrawatch/smart-gateway/pull/100 made me realise the errors being thrown when ceilometer metrics did not contain some of the fields is not the behaviour we want. Instead of an error being generated, sg-core should just skip those fields and send the rest

No error when non critical fields are not present

---

plugins/application/elasticsearch/pkg/lib/client.go

Existing code delivers 28231 messages and then stops working because it has
consumed all available outbound TCP ports.
"It is critical to both close the response body and to consume it,
in order to re-use persistent TCP connections in the default HTTP transport."
https://github.com/elastic/go-elasticsearch/blob/master/README.md#usage

Fix TCP port exhaustion

---

plugins/application/elasticsearch/main.go
plugins/application/elasticsearch/main_test.go

This patch makes use of concurrent package to fix conflicting writes/reads
to/from ES buffer when bulk index is configured

Fix concurrent conflicts in elasticsearch

---

plugins/application/elasticsearch/main.go
plugins/application/elasticsearch/main_test.go

This patch makes use of concurrent package to fix conflicting writes/reads
to/from ES buffer when bulk index is configured
Cherry picked from commit e61141ab8d2590a7b91d18cd494321af763507bd

Fix concurrent conflicts in elasticsearch (#53)

---

go.mod
pkg/lib/time.go
plugins/handler/sensubility-metrics/main.go
plugins/handler/sensubility-metrics/main_test.go
plugins/handler/sensubility-metrics/pkg/sensu/sensu.go

Move storage of container health results as a status metric in Prometheus rather than an event in Elasticsearch. Moving this logic to a separate plugin means we can reduce the complexity of the code in the original events plugin so that it does not need to handle the edge case of sensubility events (I won't do that here).

Separate plugin for handling sensubility events. Store events as metrics in Prometheus rather than Elasticsearch

---

plugins/handler/ceilometer-metrics/main.go
plugins/handler/ceilometer-metrics/messages/metric-tests.json

Ceilometer metrics report vm instance id under the 'host' label. Rename this label to 'vm_instance' for clarity

Rename instance ID key from host to vm_instance

---

cmd/main.go
cmd/manager/manager.go
config.yaml
docs/multiple-socket-plugins.md

This PR implements unique names for transport plugins, which allows us to run multiple plugins of the same type (for example 2 socket transport plugins). It also adds some notes for this in the docs/ folder.
Solves #12.

Allow to listen on multiple sockets at once

---

go.mod
plugins/application/loki/main.go
plugins/application/loki/main_test.go
plugins/application/loki/pkg/lib/loki.go

This PR makes sg-core use the most recent version of apputils and does all the required changes to the Loki plugin, which is the only one affected by the changes in apputils. Thanks to this we should be able to run the Loki plugin inside the sg-core containers. (Currently it fails, because it unsuccessfully tries to find libproton.so, even though it actually doesn't need it).

Use the current apputils and update loki plugin

---

go.mod
plugins/application/loki/main.go
plugins/transport/dummy-logs/main.go

This PR makes sg-core use the newest version of apputils.
Summary of changes in apputils:
- Ability to specify Loki tenant
- Enhanced Loki error message
- Ability to get information about processes
Only affected part by these changes is the Loki plugin (the process info isn't used anywhere). I made the required change to make the Loki plugin compatible. The Loki plugin doesn't use tenants right now and "fake" is the default tenant for Loki.
I also fixed the dummy-logs transport plugin, which wasn't working.

Update apputils and fix dummy-logs

---

build/Dockerfile

Prior to this change, I would receive this error when building sg-core
```
TASK [stf-run-ci : Create BuildConfig and ImageStream] ***************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "oc new-build -n \"service-telemetry\" --name sg-core --dockerfile - < ./working/sg-core/build/Dockerfile", "delta": "0:00:34.246661", "end": "2021-11-01 11:23:33.507520", "msg": "non-zero return code", "rc": 1, "start": "2021-11-01 11:22:59.260859", "stderr": "error: can't lookup images: Timeout: request did not complete within requested timeout context deadline exceeded\nerror: unable to locate any images in image streams, …
```

Use latest tag on Dockerfile image references

---

plugins/transport/socket/main.go
plugins/transport/socket/main_test.go

When larger than MaxBufferSize messages are being sent, the whole message processing
is failing badly. This can easily happen when socket plugin is used in Ceilometer metrics
or events processing. This patch makes it to increase buffer size, when large message is detected.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2016460

Increase reading buffer size on large messages 

---

.github/workflows/integration.yml
.github/workflows/tests.yml
build/repos/opstools.repo
ci/integration/logging/run_bridge.sh
ci/integration/logging/run_sg.sh
ci/unit/run_tests.sh

* Fix centos-opstools repo in CI
* Avoid gpgcheck for centos repo
* ... also in repo file
* Update .github/workflows/integration.yml
Co-authored-by: Matthias Runge <mrunge@redhat.com>
* Update .github/workflows/tests.yml
Co-authored-by: Matthias Runge <mrunge@redhat.com>
Co-authored-by: Leif Madsen <lmadsen@redhat.com>
Co-authored-by: Matthias Runge <mrunge@redhat.com>
(cherry picked from commit 04fc6914eaff79d50853249d7ad9dcdaabd05d9a)
(cherry picked from commit 63f8c2c596e69f46ae3657117e1bd40b24e2f30f)

Ci opstools fix (#85)

---

.github/workflows/integration.yml
.github/workflows/tests.yml
build/repos/opstools.repo
ci/integration/logging/run_bridge.sh
ci/integration/logging/run_sg.sh
ci/unit/run_tests.sh

* Fix centos-opstools repo in CI
* Avoid gpgcheck for centos repo
* ... also in repo file
* Update .github/workflows/integration.yml
Co-authored-by: Matthias Runge <mrunge@redhat.com>
* Update .github/workflows/tests.yml
Co-authored-by: Matthias Runge <mrunge@redhat.com>
Co-authored-by: Leif Madsen <lmadsen@redhat.com>
Co-authored-by: Matthias Runge <mrunge@redhat.com>
(cherry picked from commit 04fc6914eaff79d50853249d7ad9dcdaabd05d9a)
(cherry picked from commit 63f8c2c596e69f46ae3657117e1bd40b24e2f30f)
(cherry picked from commit ecd07f5ec9997cae7189c9feee80c416e89d9dce)

Ci opstools fix (#85) (#88)

---

.github/workflows/integration.yml
.github/workflows/tests.yml
build/repos/opstools.repo
ci/integration/logging/run_bridge.sh
ci/integration/logging/run_sg.sh
ci/unit/run_tests.sh

* Fix centos-opstools repo in CI
* Avoid gpgcheck for centos repo
* ... also in repo file
* Update .github/workflows/integration.yml
Co-authored-by: Matthias Runge <mrunge@redhat.com>
* Update .github/workflows/tests.yml
Co-authored-by: Matthias Runge <mrunge@redhat.com>
Co-authored-by: Leif Madsen <lmadsen@redhat.com>
Co-authored-by: Matthias Runge <mrunge@redhat.com>
(cherry picked from commit 04fc6914eaff79d50853249d7ad9dcdaabd05d9a)
(cherry picked from commit 33d41214980927458ed0f0466cb0e88ce4c7ce6b)

Ci opstools fix (#85) (#87)

---

.github/workflows/integration.yml
.github/workflows/tests.yml
build/repos/opstools.repo
ci/integration/logging/run_bridge.sh
ci/integration/logging/run_sg.sh
ci/unit/run_tests.sh
plugins/transport/socket/main.go
plugins/transport/socket/main_test.go

When larger than MaxBufferSize messages are being sent, the whole message processing
is failing badly. This can easily happen when socket plugin is used in Ceilometer metrics
or events processing.
Resolves: rhbz#2016460
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2016460
(cherry picked from commit f13e24114046d0490f0c5c611a3f83d6cd682aaf)
(cherry picked from commit 4af768f9f708098834ae6de674e64638c7445e0b)

Increase reading buffer size on large messages  (#74)

---

build/Dockerfile

Build the test plugins dummy-* for upstream builds so that when testing
with smart-gateway-operator by default the plugins exist to simulate
workloads without needing a source connected.
Changes will be used as part of the smart-gateway-operator example
CustomResource and allow for additional molecule testing in the future
for that Operator.

Build test plugins for upstream distribution

---

.github/workflows/tests.yml
go.sum

* go mod tidy
* Test with go mod download for missing deps
* Update golangci-lint action to v3
Cherry picked from commit 8216de3b809619dece201901d029a76852d10d4e

Fix golangci-lint job (#98)

---

.github/workflows/tests.yml
.golangci.yaml
build/Dockerfile
ci/integration/logging/run_sg.sh
ci/integration/metrics/run_sg.sh
ci/unit/run_tests.sh
go.mod
go.sum
pkg/config/config.go
plugins/application/alertmanager/main.go
plugins/application/alertmanager/main_test.go
plugins/application/elasticsearch/main_test.go
plugins/application/elasticsearch/pkg/lib/client.go
plugins/application/elasticsearch/pkg/lib/client_test.go
plugins/application/loki/main_test.go
plugins/application/prometheus/main.go
plugins/handler/ceilometer-metrics/main_test.go
plugins/handler/collectd-metrics/main_test.go
plugins/transport/dummy-alertmanager/main.go
plugins/transport/dummy-logs/main.go
plugins/transport/socket/main.go
plugins/transport/socket/main_test.go

This patch moves sg-core to golang 1.19. Initially I just updated the `go 1.15` line in go.mod and did `go mod tidy`. 
The build failed like this:
```
$ go version
go version go1.19.4 linux/amd64
$ ./build.sh                       
building amqp1.so                                               
[...]                               
building prometheus.so                     
asm: xxhash_amd64.s:120: when dynamic linking, R15 is clobbered by a global variable access and is used here: 00092 (/home/csibbitt/go/pkg/mod/github.com/cespare/xxhash/v2@v2.1.1/xxhash_amd6
4.s:120)   ADDQ    R15, AX         
asm: assembly failed
```
I updated that single module and the build worked:
```
$ go get github.com/cespare/xxhash/v2
go: downloading github.com/cespare/xxhash/v2 v2.2.0         
go: upgraded …
```

Move to golang 1.19

---

.github/workflows/tests.yml
.golangci.yaml
build/Dockerfile
ci/integration/logging/run_sg.sh
ci/integration/metrics/run_sg.sh
ci/unit/run_tests.sh
go.mod
go.sum
pkg/config/config.go
plugins/application/alertmanager/main.go
plugins/application/alertmanager/main_test.go
plugins/application/elasticsearch/main_test.go
plugins/application/elasticsearch/pkg/lib/client.go
plugins/application/elasticsearch/pkg/lib/client_test.go
plugins/application/loki/main_test.go
plugins/application/prometheus/main.go
plugins/handler/ceilometer-metrics/main_test.go
plugins/handler/collectd-metrics/main_test.go
plugins/transport/dummy-alertmanager/main.go
plugins/transport/dummy-logs/main.go
plugins/transport/socket/main_test.go

* Move to golang 1.19
* Found a bunch of 1.15 references in the CI machinery
* Upgrade json-iterator to 1.1.12
* Upgrade to golangci-lint 1.50
* Solve staticcheck lint
* gosec lint
* Remove deprecated linters to clear warnings
* Missing time import
* Warning from revive linter
(cherry picked from commit d343b277dc725fae0f43d012d72bf5e30a9e2324)

Move to golang 1.19 (#104)

---

cmd/manager/manager.go

Before: 
```
[ERROR] transport handlers failed to load [transport: dummy-logs0, error: missing or incorrect configuration fields --  messageField , timestampField , hostnameField , severityField --]
```
Now:
```
[ERROR] transport handlers failed to load [transport: dummy-logs0, error: failed configuring handler plugin 'logs': missing or incorrect configuration fields --  messageField , timestampField , hostnameField , severityField --]
```
Solves issue #49

Specify handler name in handler config error msg

---

.github/workflows/integration.yml
build.sh
ci/integration/logging/run_sg.sh
ci/integration/metrics/run_sg.sh

This should fix the integration CI.
It looks like the sg-core's plugins aren't inside the plugin folder. I see the following errors in the CI output when it's trying to build the plugins:
```
error obtaining VCS status: exit status 128
Use -buildvcs=false to disable VCS stamping.
```
From what I found, go >= 1.18 is adding some version control information to the built binaries and this seems to be failing right now. This PR disables that. I don't see the feature being much useful. If we decide it is useful, we can find another way.

Fix integration CI

---

devstack/plugin.sh

Often times during unstack, containers get stuck in "Stopping" state and do not get cleaned up. These left over containers cause next run of stack.sh to fail because the script tries to spawn them with the name same.

Remove sg-core & prometheus containers with force

---

.github/workflows/tests.yml
build/Dockerfile
ci/integration/logging/run_sg.sh
ci/integration/metrics/ceilometer/bridge/run_sg.sh
ci/integration/metrics/ceilometer/tcp/run_sg.sh
ci/integration/metrics/collectd/run_sg.sh
ci/unit/run_tests.sh
go.mod

* Move to golang 1.20
* Bump golangci-lint to 1.51 for golang 1.20 support
(cherry picked from commit 35d6fbeac82fc3313f8d73bca28cf5fc6f18d5cf)

Move to golang 1.20 (#127)

---

.github/workflows/integration.yml
.github/workflows/tests.yml
.github/workflows/updates.yml

Bump actions checkout to v4 since Node.js 16 actions are deprecated.
We need to update to Node.js 20, which is included in actions/checkout@v4.
Also bumps setup-go, actions-goveralls and github-script

Bump actions checkout to v4

---

.github/workflows/integration.yml
.github/workflows/tests.yml
build/repos/opstools.repo
ci/integration/logging/run_sg.sh

Centos8s went EOL on 31.05.2024 so the packages have been moved to centos vault mirror the repo config we use needs to be updated
Depends-On: https://github.com/infrawatch/sg-bridge/pull/39

Update repo info for opstools

---

.github/workflows/integration.yml
ci/integration/logging/run_bridge.sh
ci/integration/metrics/run_bridge.sh

We were missing a volume in the sg-bridge container and a package, which is required for building sg-bridge from source. I tested with a same named branch in sg-bridge repo, so the CI should be green even on a run after merge.

Fix sg-bridge in integration CI

---

.github/workflows/updates.yml

Since github-script v5, the correct syntax for adding a comment is github.rest.issues.createComment instead of github.issues.createComment
See https://github.com/marketplace/actions/github-script
Also updates the github-script to latest available version

Update coveralls update job

---

.github/workflows/integration.yml
ci/integration/logging/run_bridge.sh
ci/integration/metrics/run_bridge.sh

Fix git ls-remote command in the integration suite
The syntax should be refs/heads/GITHUB_REF

Fix git ls-remote command when running sg-bridge

---

.github/workflows/integration.yml

The deprecation of AMQP1 driver in Oslo messaging [1] broke our integration jobs
Since infrawatch/sg-core is used in STF and STF is being used with a stable OSP version, we can safely pin to the latest stable version available for Devstack and use it as a base for our integration jobs
This version corresponds with stable/2024.2, Dalmatian [2]
[1] https://github.com/openstack/oslo.messaging/commit/7997a199acada382b0c61dc84aa956e4c65de986
[2] https://docs.openstack.org/2024.2/

Pin Devstack version to stable/2024.2

---

.github/workflows/integration.yml
.github/workflows/tests.yml
.github/workflows/updates.yml

The Ubuntu 20.04 runner image will be fully unsupported by April 1, 2025.
Actions need to be updated to a newer version.
For some jobs we are already using ubuntu-latest, so use the same for the jobs using ubuntu20.04

Update GH actions to use ubuntu-latest

---

.github/workflows/integration.yml
.github/workflows/tests.yml

Avoid enabling unnecessary repos in Caracal by using the repo copy of opstools

Use repository opstools repo
